In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Vaccinations

In [2]:
dfv = pd.read_csv('../MyVizProject/data_vacc.csv', na_values='',  parse_dates=True, encoding = "ISO-8859-1")
dfv.head()

,ï»¿_id,Date,CA,CAQF,CAName,Sex,SexQF,AgeGroup,AgeGroupQF,Population,...,Dose,DoseQF,NumberVaccinated,NumberVaccinatedQF,PercentCoverage,PercentCoverageQF,CumulativeNumberVaccinated,CumulativeNumberVaccinatedQF,CumulativePercentCoverage,CumulativePercentCoverageQF
0,1,20201208,NaN,:,Unknown,Female,NaN,18 - 29,NaN,NaN,...,Dose 1,NaN,0,NaN,NaN,z,0,NaN,NaN,z
1,2,20201208,NaN,:,Unknown,Female,NaN,18 years and over,d,NaN,...,Dose 1,NaN,2,NaN,NaN,z,2,NaN,NaN,z
2,3,20201208,NaN,:,Unknown,Female,NaN,30 - 39,NaN,NaN,...,Dose 1,NaN,0,NaN,NaN,z,0,NaN,NaN,z
3,4,20201208,NaN,:,Unknown,Female,NaN,40 - 49,NaN,NaN,...,Dose 1,NaN,1,NaN,NaN,z,1,NaN,NaN,z
4,5,20201208,NaN,:,Unknown,Female,NaN,50 - 54,NaN,NaN,...,Dose 1,NaN,0,NaN,NaN,z,0,NaN,NaN,z

In [3]:
df_v = dfv[['Date','CAName','Sex', 'AgeGroup','Dose', 'NumberVaccinated']]
df_v["Date"] = pd.to_datetime(df_v.loc[:, 'Date'], format='%Y%m%d')
df_v.head()

C:\Users\Maria\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

        Date   CAName     Sex           AgeGroup    Dose  NumberVaccinated
0 2020-12-08  Unknown  Female            18 - 29  Dose 1                 0
1 2020-12-08  Unknown  Female  18 years and over  Dose 1                 2
2 2020-12-08  Unknown  Female            30 - 39  Dose 1                 0
3 2020-12-08  Unknown  Female            40 - 49  Dose 1                 1
4 2020-12-08  Unknown  Female            50 - 54  Dose 1                 0

In [4]:
df_vacc = df_v[(df_v.AgeGroup =='18 years and over') & (df_v.Sex =='Total')]
df_vacc

,Date,CAName,Sex,AgeGroup,Dose,NumberVaccinated
23,2020-12-08,Unknown,Total,18 years and over,Dose 1,4
57,2020-12-08,Unknown,Total,18 years and over,Dose 2,0
91,2020-12-08,Clackmannanshire,Total,18 years and over,Dose 1,66
125,2020-12-08,Clackmannanshire,Total,18 years and over,Dose 2,0
159,2020-12-08,Dumfries and Galloway,Total,18 years and over,Dose 1,35
...,...,...,...,...,...,...
489045,2021-07-13,Perth and Kinross,Total,18 years and over,Dose 2,286
489079,2021-07-13,Glasgow City,Total,18 years and over,Dose 1,1336
489113,2021-07-13,Glasgow City,Total,18 years and over,Dose 2,1845
489147,2021-07-13,North Lanarkshire,Total,18 years and over,Dose 1,82
489181,2021-07-13,North Lanarkshire,Total,18 years and over,Dose 2,116

In [5]:
print("Date range is: " + str(df_v.Date.min()) +' to '+ str(df_v.Date.max()))

Date range is: 2020-12-08 00:00:00 to 2021-07-13 00:00:00

In [6]:
df_vacc = df_vacc[(df_vacc.CAName!='Unknown')]
df_vacc = df_vacc[['Date','CAName','NumberVaccinated']]
df_vacc.head()

          Date                 CAName  NumberVaccinated
91  2020-12-08       Clackmannanshire                66
125 2020-12-08       Clackmannanshire                 0
159 2020-12-08  Dumfries and Galloway                35
193 2020-12-08  Dumfries and Galloway                 0
227 2020-12-08          East Ayrshire                46

In [7]:
s = df_vacc.groupby(['Date', 'CAName'])['NumberVaccinated'].sum()
s

Date        CAName
2020-12-08  Aberdeen City           11
            Aberdeenshire           18
            Angus                   16
            Argyll and Bute          1
            City of Edinburgh      395
                                  ...
2021-07-13  South Ayrshire          23
            South Lanarkshire      267
            Stirling               240
            West Dunbartonshire    406
            West Lothian           958
Name: NumberVaccinated, Length: 6976, dtype: int64

In [8]:
type(df_vacc_g)

pandas.core.series.Series

In [8]:
df_vacc_g = s.unstack(level=1)
df_vacc_g.head(10)

CAName,Aberdeen City,Aberdeenshire,Angus,Argyll and Bute,City of Edinburgh,Clackmannanshire,Dumfries and Galloway,Dundee City,East Ayrshire,East Dunbartonshire,...,Orkney Islands,Perth and Kinross,Renfrewshire,Scottish Borders,Shetland Islands,South Ayrshire,South Lanarkshire,Stirling,West Dunbartonshire,West Lothian
Date,,,,,,,,,,,,,,,,,,,,,
2020-12-08,11,18,16,1,395,66,35,18,46,25,...,0,26,12,54,0,29,31,175,10,151
2020-12-09,5,1,32,2,940,97,68,82,137,46,...,50,51,36,101,0,95,77,210,8,307
2020-12-10,84,41,80,5,839,118,71,199,191,70,...,78,104,146,59,0,130,109,224,57,328
2020-12-11,127,63,89,76,788,43,76,210,215,66,...,54,104,154,102,11,219,285,71,62,321
2020-12-12,4,2,54,4,261,32,0,208,89,74,...,0,114,101,7,0,93,54,51,24,263
2020-12-13,3,2,68,1,240,27,0,167,0,2,...,0,127,2,3,0,1,8,35,1,251
2020-12-14,233,330,89,25,719,50,152,171,22,120,...,45,86,232,25,11,6,368,50,82,185
2020-12-15,470,545,74,161,466,211,303,175,105,156,...,25,130,380,47,7,186,574,151,78,155
2020-12-16,399,408,55,192,656,57,349,95,164,178,...,65,167,131,23,13,193,319,166,191,115
2020-12-17,406,438,41,301,501,27,363,122,153,160,...,41,38,144,197,40,140,523,40,272,211

In [10]:
cols = ['Aberdeen City', 'Aberdeenshire', 'Angus', 'Argyll and Bute',
       'City of Edinburgh', 'Clackmannanshire', 'Dumfries and Galloway',
       'Dundee City', 'East Ayrshire', 'East Dunbartonshire', 'East Lothian',
       'East Renfrewshire', 'Falkirk', 'Fife', 'Glasgow City', 'Highland',
       'Inverclyde', 'Midlothian', 'Moray', 'Na h-Eileanan Siar',
       'North Ayrshire', 'North Lanarkshire', 'Orkney Islands',
       'Perth and Kinross', 'Renfrewshire', 'Scottish Borders',
       'Shetland Islands', 'South Ayrshire', 'South Lanarkshire', 'Stirling',
       'West Dunbartonshire', 'West Lothian']

In [30]:
df_vacc_g.columns

Index(['Aberdeen City', 'Aberdeenshire', 'Angus', 'Argyll and Bute',
       'City of Edinburgh', 'Clackmannanshire', 'Dumfries and Galloway',
       'Dundee City', 'East Ayrshire', 'East Dunbartonshire', 'East Lothian',
       'East Renfrewshire', 'Falkirk', 'Fife', 'Glasgow City', 'Highland',
       'Inverclyde', 'Midlothian', 'Moray', 'Na h-Eileanan Siar',
       'North Ayrshire', 'North Lanarkshire', 'Orkney Islands',
       'Perth and Kinross', 'Renfrewshire', 'Scottish Borders',
       'Shetland Islands', 'South Ayrshire', 'South Lanarkshire', 'Stirling',
       'West Dunbartonshire', 'West Lothian'],
      dtype='object', name='CAName')

In [13]:
df_vacc_g.index

DatetimeIndex(['2020-12-08', '2020-12-09', '2020-12-10', '2020-12-11',
               '2020-12-12', '2020-12-13', '2020-12-14', '2020-12-15',
               '2020-12-16', '2020-12-17',
               ...
               '2021-06-11', '2021-06-12', '2021-06-13', '2021-06-14',
               '2021-06-15', '2021-06-16', '2021-06-17', '2021-06-18',
               '2021-06-19', '2021-06-20'],
              dtype='datetime64[ns]', name='Date', length=195, freq=None)

In [13]:
df_vacc_g.index

MultiIndex([('2020-12-08',         'Aberdeen City'),
            ('2020-12-08',         'Aberdeenshire'),
            ('2020-12-08',                 'Angus'),
            ('2020-12-08',       'Argyll and Bute'),
            ('2020-12-08',     'City of Edinburgh'),
            ('2020-12-08',      'Clackmannanshire'),
            ('2020-12-08', 'Dumfries and Galloway'),
            ('2020-12-08',           'Dundee City'),
            ('2020-12-08',         'East Ayrshire'),
            ('2020-12-08',   'East Dunbartonshire'),
            ...
            ('2021-06-20',        'Orkney Islands'),
            ('2021-06-20',     'Perth and Kinross'),
            ('2021-06-20',          'Renfrewshire'),
            ('2021-06-20',      'Scottish Borders'),
            ('2021-06-20',      'Shetland Islands'),
            ('2021-06-20',        'South Ayrshire'),
            ('2021-06-20',     'South Lanarkshire'),
            ('2021-06-20',              'Stirling'),
            ('2021-06-20',   'West Dunbartonshire'),
            ('2021-06-20',          'West Lothian')],
           names=['Date', 'CAName'], length=6240)

In [9]:
s = df_vacc.stack(level=0)
s

91      Date                2020-12-08 00:00:00
        CAName                 Clackmannanshire
        NumberVaccinated                     66
125     Date                2020-12-08 00:00:00
        CAName                 Clackmannanshire
                                   ...
489147  CAName                North Lanarkshire
        NumberVaccinated                     82
489181  Date                2021-07-13 00:00:00
        CAName                North Lanarkshire
        NumberVaccinated                    116
Length: 41856, dtype: object

In [10]:
df_vaccs22 = (((df_vacc_g.rolling(7)).mean())).shift(22).rolling(1).mean().fillna(0).round()
df_vaccs23 = (((df_vacc_g.rolling(7)).mean())).shift(23).rolling(1).mean().fillna(0).round()
df_vaccs24 = (((df_vacc_g.rolling(7)).mean())).shift(24).rolling(1).mean().fillna(0).round()
df_vaccs25 = (((df_vacc_g.rolling(7)).mean())).shift(25).rolling(1).mean().fillna(0).round()
df_vaccs26 = (((df_vacc_g.rolling(7)).mean())).shift(26).rolling(1).mean().fillna(0).round()
df_vaccs27 = (((df_vacc_g.rolling(7)).mean())).shift(27).rolling(1).mean().fillna(0).round()
df_vaccs28 = (((df_vacc_g.rolling(7)).mean())).shift(28).rolling(1).mean().fillna(0).round()
df_vaccs29 = (((df_vacc_g.rolling(7)).mean())).shift(29).rolling(1).mean().fillna(0).round()
df_vaccs30 = (((df_vacc_g.rolling(7)).mean())).shift(30).rolling(1).mean().fillna(0).round()
df_vaccs31 = (((df_vacc_g.rolling(7)).mean())).shift(31).rolling(1).mean().fillna(0).round()
df_vaccs32 = (((df_vacc_g.rolling(7)).mean())).shift(32).rolling(1).mean().fillna(0).round()
df_vaccs33 = (((df_vacc_g.rolling(7)).mean())).shift(33).rolling(1).mean().fillna(0).round()
df_vaccs34 = (((df_vacc_g.rolling(7)).mean())).shift(34).rolling(1).mean().fillna(0).round()
df_vaccs35 = (((df_vacc_g.rolling(7)).mean())).shift(35).rolling(1).mean().fillna(0).round()
df_vaccs36 = (((df_vacc_g.rolling(7)).mean())).shift(36).rolling(1).mean().fillna(0).round()
df_vaccs37 = (((df_vacc_g.rolling(7)).mean())).shift(37).rolling(1).mean().fillna(0).round()
df_vaccs38 = (((df_vacc_g.rolling(7)).mean())).shift(38).rolling(1).mean().fillna(0).round()
df_vaccs39 = (((df_vacc_g.rolling(7)).mean())).shift(39).rolling(1).mean().fillna(0).round()
df_vaccs40 = (((df_vacc_g.rolling(7)).mean())).shift(40).rolling(1).mean().fillna(0).round()
df_vaccs41 = (((df_vacc_g.rolling(7)).mean())).shift(41).rolling(1).mean().fillna(0).round()
df_vaccs42 = (((df_vacc_g.rolling(7)).mean())).shift(42).rolling(1).mean().fillna(0).round()
df_vaccs43 = (((df_vacc_g.rolling(7)).mean())).shift(43).rolling(1).mean().fillna(0).round()
df_vaccs44 = (((df_vacc_g.rolling(7)).mean())).shift(44).rolling(1).mean().fillna(0).round()
df_vaccs45 = (((df_vacc_g.rolling(7)).mean())).shift(45).rolling(1).mean().fillna(0).round()
df_vaccs46 = (((df_vacc_g.rolling(7)).mean())).shift(46).rolling(1).mean().fillna(0).round()
df_vaccs47 = (((df_vacc_g.rolling(7)).mean())).shift(47).rolling(1).mean().fillna(0).round()
df_vaccs48 = (((df_vacc_g.rolling(7)).mean())).shift(48).rolling(1).mean().fillna(0).round()
df_vaccs49 = (((df_vacc_g.rolling(7)).mean())).shift(49).rolling(1).mean().fillna(0).round()
df_vaccs50 = (((df_vacc_g.rolling(7)).mean())).shift(50).rolling(1).mean().fillna(0).round()
df_vaccs51 = (((df_vacc_g.rolling(7)).mean())).shift(51).rolling(1).mean().fillna(0).round()
df_vaccs52 = (((df_vacc_g.rolling(7)).mean())).shift(52).rolling(1).mean().fillna(0).round()
df_vaccs53 = (((df_vacc_g.rolling(7)).mean())).shift(53).rolling(1).mean().fillna(0).round()
df_vaccs54 = (((df_vacc_g.rolling(7)).mean())).shift(54).rolling(1).mean().fillna(0).round()
df_vaccs55 = (((df_vacc_g.rolling(7)).mean())).shift(55).rolling(1).mean().fillna(0).round()
df_vaccs56 = (((df_vacc_g.rolling(7)).mean())).shift(56).rolling(1).mean().fillna(0).round()
df_vaccs57 = (((df_vacc_g.rolling(7)).mean())).shift(57).rolling(1).mean().fillna(0).round()
df_vaccs58 = (((df_vacc_g.rolling(7)).mean())).shift(58).rolling(1).mean().fillna(0).round()
df_vaccs59 = (((df_vacc_g.rolling(7)).mean())).shift(59).rolling(1).mean().fillna(0).round()
df_vaccs60 = (((df_vacc_g.rolling(7)).mean())).shift(60).rolling(1).mean().fillna(0).round()
df_vaccs61 = (((df_vacc_g.rolling(7)).mean())).shift(61).rolling(1).mean().fillna(0).round()
df_vaccs62 = (((df_vacc_g.rolling(7)).mean())).shift(62).rolling(1).mean().fillna(0).round()
df_vaccs63 = (((df_vacc_g.rolling(7)).mean())).shift(63).rolling(1).mean().fillna(0).round()
df_vaccs64 = (((df_vacc_g.rolling(7)).mean())).shift(64).rolling(1).mean().fillna(0).round()
df_vaccs65 = (((df_vacc_g.rolling(7)).mean())).shift(65).rolling(1).mean().fillna(0).round()
df_vaccs66 = (((df_vacc_g.rolling(7)).mean())).shift(66).rolling(1).mean().fillna(0).round()
df_vaccs67 = (((df_vacc_g.rolling(7)).mean())).shift(67).rolling(1).mean().fillna(0).round()
df_vaccs68 = (((df_vacc_g.rolling(7)).mean())).shift(68).rolling(1).mean().fillna(0).round()
df_vaccs69 = (((df_vacc_g.rolling(7)).mean())).shift(69).rolling(1).mean().fillna(0).round()
df_vaccs70 = (((df_vacc_g.rolling(7)).mean())).shift(70).rolling(1).mean().fillna(0).round()
df_vaccs71 = (((df_vacc_g.rolling(7)).mean())).shift(71).rolling(1).mean().fillna(0).round()
df_vaccs72 = (((df_vacc_g.rolling(7)).mean())).shift(72).rolling(1).mean().fillna(0).round()
df_vaccs73 = (((df_vacc_g.rolling(7)).mean())).shift(73).rolling(1).mean().fillna(0).round()
df_vaccs74 = (((df_vacc_g.rolling(7)).mean())).shift(74).rolling(1).mean().fillna(0).round()
df_vaccs75 = (((df_vacc_g.rolling(7)).mean())).shift(75).rolling(1).mean().fillna(0).round()
df_vaccs76 = (((df_vacc_g.rolling(7)).mean())).shift(76).rolling(1).mean().fillna(0).round()
df_vaccs77 = (((df_vacc_g.rolling(7)).mean())).shift(77).rolling(1).mean().fillna(0).round()
df_vaccs78 = (((df_vacc_g.rolling(7)).mean())).shift(78).rolling(1).mean().fillna(0).round()
df_vaccs79 = (((df_vacc_g.rolling(7)).mean())).shift(79).rolling(1).mean().fillna(0).round()
df_vaccs80 = (((df_vacc_g.rolling(7)).mean())).shift(80).rolling(1).mean().fillna(0).round()
df_vaccs81 = (((df_vacc_g.rolling(7)).mean())).shift(81).rolling(1).mean().fillna(0).round()
df_vaccs82 = (((df_vacc_g.rolling(7)).mean())).shift(82).rolling(1).mean().fillna(0).round()
df_vaccs83 = (((df_vacc_g.rolling(7)).mean())).shift(83).rolling(1).mean().fillna(0).round()
df_vaccs84 = (((df_vacc_g.rolling(7)).mean())).shift(84).rolling(1).mean().fillna(0).round()
df_vaccs85 = (((df_vacc_g.rolling(7)).mean())).shift(85).rolling(1).mean().fillna(0).round()
df_vaccs86 = (((df_vacc_g.rolling(7)).mean())).shift(86).rolling(1).mean().fillna(0).round()
df_vaccs87 = (((df_vacc_g.rolling(7)).mean())).shift(87).rolling(1).mean().fillna(0).round()
df_vaccs88 = (((df_vacc_g.rolling(7)).mean())).shift(88).rolling(1).mean().fillna(0).round()
df_vaccs89 = (((df_vacc_g.rolling(7)).mean())).shift(89).rolling(1).mean().fillna(0).round()
df_vaccs90 = (((df_vacc_g.rolling(7)).mean())).shift(90).rolling(1).mean().fillna(0).round()

In [11]:
mylist_la = [df_vaccs22, df_vaccs23, df_vaccs24, df_vaccs25, df_vaccs26, df_vaccs27, df_vaccs28, df_vaccs29,
          df_vaccs30, df_vaccs31, df_vaccs32, df_vaccs33, df_vaccs34, df_vaccs35, df_vaccs36, df_vaccs37, df_vaccs38, df_vaccs39,
          df_vaccs40, df_vaccs41, df_vaccs42, df_vaccs43, df_vaccs44, df_vaccs45, df_vaccs46, df_vaccs47, df_vaccs48, df_vaccs49,
          df_vaccs50, df_vaccs51, df_vaccs52, df_vaccs53, df_vaccs54, df_vaccs55, df_vaccs56, df_vaccs57, df_vaccs58, df_vaccs59,
          df_vaccs60, df_vaccs61, df_vaccs62, df_vaccs63, df_vaccs64, df_vaccs65, df_vaccs66, df_vaccs67, df_vaccs68, df_vaccs69,
          df_vaccs70, df_vaccs71, df_vaccs72, df_vaccs73, df_vaccs74, df_vaccs75, df_vaccs76, df_vaccs77, df_vaccs78, df_vaccs79,
          df_vaccs80, df_vaccs81, df_vaccs82, df_vaccs83, df_vaccs84, df_vaccs85, df_vaccs86, df_vaccs87, df_vaccs88, df_vaccs89,
          df_vaccs90]

In [12]:
from functools import reduce

df_v = reduce(lambda i, j: i.add(j, fill_value=0), mylist_la)
#df_v.NumberVaccinated = df_vacc_all.NumberVaccinated.astype(int)
df_v.head(50)

CAName,Aberdeen City,Aberdeenshire,Angus,Argyll and Bute,City of Edinburgh,Clackmannanshire,Dumfries and Galloway,Dundee City,East Ayrshire,East Dunbartonshire,...,Orkney Islands,Perth and Kinross,Renfrewshire,Scottish Borders,Shetland Islands,South Ayrshire,South Lanarkshire,Stirling,West Dunbartonshire,West Lothian
Date,,,,,,,,,,,,,,,,,,,,,
2020-12-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-12-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021-01-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021-01-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021-01-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021-01-05,67.0,65.0,61.0,16.0,597.0,62.0,57.0,151.0,100.0,58.0,...,32.0,87.0,98.0,50.0,3.0,82.0,133.0,117.0,35.0,258.0
2021-01-06,199.0,206.0,130.0,55.0,1205.0,145.0,153.0,324.0,208.0,134.0,...,68.0,189.0,248.0,99.0,7.0,186.0,344.0,230.0,80.0,517.0
2021-01-07,388.0,405.0,203.0,121.0,1772.0,222.0,289.0,499.0,320.0,229.0,...,106.0,308.0,412.0,137.0,13.0,304.0,589.0,337.0,151.0,748.0
2021-01-08,623.0,660.0,270.0,230.0,2291.0,286.0,467.0,663.0,427.0,337.0,...,139.0,417.0,575.0,195.0,25.0,424.0,893.0,418.0,252.0,962.0
2021-01-09,891.0,1042.0,329.0,372.0,2788.0,347.0,682.0,805.0,524.0,474.0,...,173.0,541.0,741.0,292.0,43.0,536.0,1248.0,497.0,395.0,1152.0
2021-01-10,1160.0,1450.0,389.0,515.0,3278.0,407.0,897.0,937.0,610.0,639.0,...,207.0,678.0,925.0,427.0,61.0,636.0,1624.0,575.0,547.0,1318.0
2021-01-11,1431.0,1886.0,487.0,658.0,3762.0,463.0,1112.0,1066.0,698.0,820.0,...,241.0,827.0,1133.0,611.0,79.0,736.0,2013.0,649.0,701.0,1458.0
2021-01-12,1761.0,2370.0,621.0,799.0,4290.0,520.0,1365.0,1216.0,811.0,1006.0,...,273.0,1008.0,1336.0,818.0,100.0,866.0,2417.0,745.0,858.0,1609.0
2021-01-13,2123.0,2925.0,788.0,923.0,4900.0,573.0,1639.0,1389.0,945.0,1197.0,...,316.0,1237.0,1521.0,1074.0,126.0,1005.0,2850.0,844.0,1021.0,1772.0
2021-01-14,2495.0,3545.0,1001.0,1058.0,5532.0,626.0,1923.0,1602.0,1090.0,1383.0,...,360.0,1493.0,1714.0,1365.0,152.0,1146.0,3325.0,930.0,1177.0,1958.0
2021-01-15,2838.0,4106.0,1225.0,1157.0,6138.0,675.0,2165.0,1805.0,1219.0,1555.0,...,399.0,1745.0,1894.0,1655.0,174.0,1272.0,3762.0,1011.0,1307.0,2118.0
2021-01-16,3129.0,4532.0,1444.0,1211.0,6653.0,720.0,2359.0,2000.0,1327.0,1688.0,...,429.0,1967.0,2049.0,1891.0,188.0,1374.0,4108.0,1083.0,1386.0,2256.0
2021-01-17,3419.0,4931.0,1655.0,1264.0,7138.0,762.0,2552.0,2175.0,1433.0,1783.0,...,459.0,2160.0,2171.0,2088.0,202.0,1475.0,4425.0,1149.0,1453.0,2381.0
2021-01-18,3707.0,5303.0,1818.0,1316.0,7596.0,804.0,2745.0,2329.0,1538.0,1874.0,...,489.0,2324.0,2280.0,2236.0,216.0,1575.0,4729.0,1213.0,1518.0,2496.0
2021-01-19,3920.0,5583.0,1932.0,1367.0,7907.0,838.0,2896.0,2438.0,1637.0,1954.0,...,515.0,2445.0,2381.0,2358.0,225.0,1669.0,4999.0,1249.0,1570.0,2574.0
2021-01-20,4125.0,5753.0,2055.0,1416.0,8122.0,853.0,3007.0,2558.0,1731.0,2036.0,...,531.0,2532.0,2480.0,2460.0,231.0,1760.0,5250.0,1280.0,1623.0,2645.0
2021-01-21,4322.0,5828.0,2162.0,1430.0,8290.0,868.0,3075.0,2673.0,1824.0,2117.0,...,542.0,2608.0,2593.0,2544.0,245.0,1861.0,5490.0,1319.0,1675.0,2704.0
2021-01-22,4552.0,5931.0,2281.0,1438.0,8433.0,885.0,3134.0,2823.0,1917.0,2196.0,...,559.0,2719.0,2715.0,2611.0,264.0,1974.0,5748.0,1361.0,1717.0,2773.0
2021-01-23,4783.0,6035.0,2400.0,1446.0,8576.0,902.0,3193.0,2973.0,2010.0,2275.0,...,576.0,2830.0,2837.0,2678.0,283.0,2087.0,6006.0,1403.0,1759.0,2842.0
2021-01-24,5015.0,6139.0,2519.0,1454.0,8720.0,919.0,3252.0,3123.0,2103.0,2354.0,...,593.0,2941.0,2959.0,2745.0,302.0,2200.0,6264.0,1445.0,1801.0,2912.0
2021-01-25,5248.0,6243.0,2638.0,1462.0,8863.0,936.0,3311.0,3273.0,2196.0,2422.0,...,610.0,3052.0,3070.0,2812.0,321.0,2313.0,6521.0,1487.0,1842.0,2982.0
2021-01-26,5508.0,6352.0,2758.0,1470.0,9007.0,953.0,3376.0,3446.0,2286.0,2479.0,...,627.0,3188.0,3173.0,2879.0,340.0,2409.0,6746.0,1529.0,1882.0,3051.0

In [13]:
df_v = df_v.stack().copy()
df_v

Date        CAName
2020-12-08  Aberdeen City               0.0
            Aberdeenshire               0.0
            Angus                       0.0
            Argyll and Bute             0.0
            City of Edinburgh           0.0
                                     ...
2021-07-13  South Ayrshire          65700.0
            South Lanarkshire      189194.0
            Stirling                52261.0
            West Dunbartonshire     41981.0
            West Lothian           108002.0
Length: 6976, dtype: float64

In [14]:
df_v1 = df_v.to_frame().reset_index()
df_v1.set_index('Date',inplace=True)
df_v1.rename(columns={'CAName':'Council',0:'Vaccinations_per_LA'}, inplace=True)
df_v1.Vaccinations_per_LA = df_v1.Vaccinations_per_LA.round(0).astype(int)
df_v1

                        Council  Vaccinations_per_LA
Date
2020-12-08        Aberdeen City                    0
2020-12-08        Aberdeenshire                    0
2020-12-08                Angus                    0
2020-12-08      Argyll and Bute                    0
2020-12-08    City of Edinburgh                    0
...                         ...                  ...
2021-07-13       South Ayrshire                65700
2021-07-13    South Lanarkshire               189194
2021-07-13             Stirling                52261
2021-07-13  West Dunbartonshire                41981
2021-07-13         West Lothian               108002

[6976 rows x 2 columns]

In [15]:
vacc = df_v1.loc[(df_v1.index>='2021-01-05')&(df_v1.index<='2021-06-30')]
vacc.to_csv('output_vaccs_la.csv')
vacc.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5664 entries, 2021-01-05 to 2021-06-30
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Council              5664 non-null   object
 1   Vaccinations_per_LA  5664 non-null   int32
dtypes: int32(1), object(1)
memory usage: 110.6+ KB

## Cases and Deaths

In [16]:
df = pd.read_csv('../MyVizProject/data_cases_la.csv',na_values='',encoding = "ISO-8859-1")
df.head()

,ï»¿_id,Date,CA,CAName,DailyPositive,CumulativePositive,CrudeRatePositive,CrudeRate7DayPositive,DailyDeaths,CumulativeDeaths,...,CumulativeNegative,CrudeRateNegative,TotalTests,PositiveTests,PositivePercentage,PositivePercentage7Day,TotalPillar1,TotalPillar2,PositivePillar1,PositivePillar2
0,1,20200228,S12000005,Clackmannanshire,0,0,0.0,NaN,0,0,...,4,7.760962,6,0,0.0,0.0,6,0,0,0
1,2,20200228,S12000006,Dumfries & Galloway,0,0,0.0,NaN,0,0,...,9,6.045949,9,0,0.0,0.0,9,0,0,0
2,3,20200228,S12000008,East Ayrshire,0,0,0.0,NaN,0,0,...,0,0.000000,1,0,0.0,0.0,1,0,0,0
3,4,20200228,S12000010,East Lothian,0,0,0.0,NaN,0,0,...,7,6.536558,7,0,0.0,0.0,7,0,0,0
4,5,20200228,S12000011,East Renfrewshire,0,0,0.0,NaN,0,0,...,2,2.093583,3,0,0.0,0.0,3,0,0,0

In [17]:
df = df.rename(columns = {'ï»¿_id':'id'})
df["Date"] = pd.to_datetime(df.loc[:, 'Date'], format='%Y%m%d')

In [18]:
df_cases = df[(df.CAName!='Unknown')]
df_cases = df_cases[[ 'Date', 'CAName', 'DailyPositive']]#.set_index('Date')
df_cases.head()

        Date               CAName  DailyPositive
0 2020-02-28     Clackmannanshire              0
1 2020-02-28  Dumfries & Galloway              0
2 2020-02-28        East Ayrshire              0
3 2020-02-28         East Lothian              0
4 2020-02-28    East Renfrewshire              0

In [19]:
sc = df_cases.groupby(['Date', 'CAName'])['DailyPositive'].sum()
sc

Date        CAName
2020-02-28  Aberdeen City           0
            Aberdeenshire           0
            Angus                   1
            Argyll & Bute           0
            City of Edinburgh       0
                                   ..
2021-07-14  South Ayrshire         11
            South Lanarkshire      41
            Stirling                3
            West Dunbartonshire     3
            West Lothian            4
Name: DailyPositive, Length: 16096, dtype: int64

In [24]:
df_cases_g = sc.unstack(level=1)
df_cases_g.tail(10)

CAName,Aberdeen City,Aberdeenshire,Angus,Argyll & Bute,City of Edinburgh,Clackmannanshire,Dumfries & Galloway,Dundee City,East Ayrshire,East Dunbartonshire,...,Orkney Islands,Perth & Kinross,Renfrewshire,Scottish Borders,Shetland Islands,South Ayrshire,South Lanarkshire,Stirling,West Dunbartonshire,West Lothian
Date,,,,,,,,,,,,,,,,,,,,,
2021-07-05,143,101,84,26,439,21,39,180,63,64,...,1,94,115,54,0,45,165,38,59,110
2021-07-06,133,107,87,33,393,22,28,141,49,71,...,6,104,119,57,1,22,111,44,63,103
2021-07-07,107,72,86,20,378,20,18,150,30,54,...,9,84,75,48,6,38,139,40,62,113
2021-07-08,135,81,74,20,350,11,24,119,31,46,...,3,67,102,30,1,36,121,33,33,107
2021-07-09,106,67,69,23,300,8,30,92,25,53,...,8,64,73,28,2,28,94,34,54,98
2021-07-10,70,53,47,6,255,6,21,85,24,30,...,0,53,68,21,3,30,86,24,30,64
2021-07-11,83,68,66,10,267,6,15,85,33,29,...,0,34,79,19,4,20,102,17,36,66
2021-07-12,96,84,85,21,315,13,31,96,38,36,...,6,99,99,52,9,32,125,36,46,70
2021-07-13,82,92,61,17,258,12,49,90,38,36,...,1,55,113,41,8,25,134,29,34,67
2021-07-14,10,2,10,5,25,0,10,28,2,16,...,0,5,22,4,13,11,41,3,3,4

In [25]:
df_c = ((df_cases_g.rolling(7).mean())).shift(-7).rolling(1).mean().fillna(0)
# shift(-7) moves it back by 7 days to the day of exposure.
df_c.tail(10)

CAName,Aberdeen City,Aberdeenshire,Angus,Argyll & Bute,City of Edinburgh,Clackmannanshire,Dumfries & Galloway,Dundee City,East Ayrshire,East Dunbartonshire,...,Orkney Islands,Perth & Kinross,Renfrewshire,Scottish Borders,Shetland Islands,South Ayrshire,South Lanarkshire,Stirling,West Dunbartonshire,West Lothian
Date,,,,,,,,,,,,,,,,,,,,,
2021-07-05,104.285714,76.000000,73.428571,19.000000,322.571429,12.285714,23.857143,109.714286,32.857143,45.571429,...,4.571429,72.142857,87.857143,36.428571,3.714286,29.428571,111.142857,32.571429,46.285714,88.714286
2021-07-06,97.000000,73.857143,69.714286,16.714286,303.285714,10.857143,26.857143,102.428571,31.285714,40.571429,...,3.857143,65.142857,87.000000,34.142857,4.714286,29.857143,114.428571,30.428571,42.142857,83.571429
2021-07-07,83.142857,63.857143,58.857143,14.571429,252.857143,8.000000,25.714286,85.000000,27.285714,35.142857,...,2.571429,53.857143,79.428571,27.857143,5.714286,26.000000,100.428571,25.142857,33.714286,68.000000
2021-07-08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2021-07-09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2021-07-10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2021-07-11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2021-07-12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2021-07-13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2021-07-14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [26]:
df_c = df_c.stack().copy()
df_c

Date        CAName
2020-02-28  Aberdeen City          0.142857
            Aberdeenshire          0.142857
            Angus                  0.000000
            Argyll & Bute          0.000000
            City of Edinburgh      0.285714
                                     ...
2021-07-14  South Ayrshire         0.000000
            South Lanarkshire      0.000000
            Stirling               0.000000
            West Dunbartonshire    0.000000
            West Lothian           0.000000
Length: 16096, dtype: float64

In [27]:
df_c1 = df_c.to_frame().reset_index()
df_c1.set_index('Date',inplace=True)
df_c1.rename(columns={'CAName':'Council',0:'Positive_Cases_per_LA'}, inplace=True)
df_c1.Positive_Cases_per_LA = df_c1.Positive_Cases_per_LA.round(0).astype(int)
df_c1

                        Council  Positive_Cases_per_LA
Date
2020-02-28        Aberdeen City                      0
2020-02-28        Aberdeenshire                      0
2020-02-28                Angus                      0
2020-02-28        Argyll & Bute                      0
2020-02-28    City of Edinburgh                      0
...                         ...                    ...
2021-07-14       South Ayrshire                      0
2021-07-14    South Lanarkshire                      0
2021-07-14             Stirling                      0
2021-07-14  West Dunbartonshire                      0
2021-07-14         West Lothian                      0

[16096 rows x 2 columns]

In [28]:
cases = df_c1.loc[(df_c1.index>='2021-01-05')&(df_c1.index<='2021-06-30')]
cases.to_csv('output_cases_la.csv')
#cases.tail(20)

In [29]:
df_deaths = df[(df.CAName!='Unknown')]
df_deaths = df_deaths[[ 'Date', 'CAName', 'DailyDeaths']]#.set_index('Date')
df_deaths.head()

        Date               CAName  DailyDeaths
0 2020-02-28     Clackmannanshire            0
1 2020-02-28  Dumfries & Galloway            0
2 2020-02-28        East Ayrshire            0
3 2020-02-28         East Lothian            0
4 2020-02-28    East Renfrewshire            0

In [30]:
sd = df_deaths.groupby(['Date', 'CAName'])['DailyDeaths'].sum()
sd

Date        CAName
2020-02-28  Aberdeen City          0
            Aberdeenshire          0
            Angus                  0
            Argyll & Bute          0
            City of Edinburgh      0
                                  ..
2021-07-14  South Ayrshire         0
            South Lanarkshire      0
            Stirling               0
            West Dunbartonshire    0
            West Lothian           0
Name: DailyDeaths, Length: 16096, dtype: int64

In [31]:
df_deaths_g = sd.unstack(level=1)
df_deaths_g.tail(10)

CAName,Aberdeen City,Aberdeenshire,Angus,Argyll & Bute,City of Edinburgh,Clackmannanshire,Dumfries & Galloway,Dundee City,East Ayrshire,East Dunbartonshire,...,Orkney Islands,Perth & Kinross,Renfrewshire,Scottish Borders,Shetland Islands,South Ayrshire,South Lanarkshire,Stirling,West Dunbartonshire,West Lothian
Date,,,,,,,,,,,,,,,,,,,,,
2021-07-05,0,0,0,0,0,0,0,2,0,0,...,0,1,0,0,0,0,1,0,0,0
2021-07-06,0,0,0,0,0,1,0,2,0,0,...,0,0,0,0,0,0,1,0,0,0
2021-07-07,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2021-07-08,0,0,0,0,2,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
2021-07-09,0,0,0,0,2,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2021-07-10,0,0,0,0,1,0,0,0,0,0,...,0,1,0,1,0,0,0,0,0,0
2021-07-11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2021-07-12,0,0,0,0,0,0,0,0,1,0,...,0,2,0,0,0,0,0,0,0,0
2021-07-13,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2021-07-14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [33]:
df_d = (df_deaths_g.rolling(7).mean()).shift(-14).rolling(1).mean().fillna(0)
df_d.tail(30)

CAName,Aberdeen City,Aberdeenshire,Angus,Argyll & Bute,City of Edinburgh,Clackmannanshire,Dumfries & Galloway,Dundee City,East Ayrshire,East Dunbartonshire,...,Orkney Islands,Perth & Kinross,Renfrewshire,Scottish Borders,Shetland Islands,South Ayrshire,South Lanarkshire,Stirling,West Dunbartonshire,West Lothian
Date,,,,,,,,,,,,,,,,,,,,,
2021-06-15,0.0,0.142857,0.142857,5.551115e-17,0.142857,0.285714,0.000000,0.285714,0.142857,0.000000,...,0.0,0.285714,5.329071e-15,0.000000,0.0,0.142857,0.285714,0.0,1.332268e-15,0.000000
2021-06-16,0.0,0.142857,0.142857,5.551115e-17,0.285714,0.285714,0.000000,0.285714,0.000000,0.000000,...,0.0,0.285714,5.329071e-15,0.000000,0.0,0.142857,0.285714,0.0,1.332268e-15,0.000000
2021-06-17,0.0,0.142857,0.142857,5.551115e-17,0.285714,0.285714,0.000000,0.285714,0.000000,0.000000,...,0.0,0.142857,5.329071e-15,0.000000,0.0,0.142857,0.142857,0.0,1.332268e-15,0.142857
2021-06-18,0.0,0.142857,0.142857,5.551115e-17,0.142857,0.285714,0.000000,0.285714,0.000000,0.000000,...,0.0,0.285714,5.329071e-15,0.000000,0.0,0.142857,0.142857,0.0,1.332268e-15,0.142857
2021-06-19,0.0,0.000000,0.142857,1.428571e-01,0.142857,0.285714,0.000000,0.000000,0.000000,0.000000,...,0.0,0.142857,5.329071e-15,0.000000,0.0,0.142857,0.142857,0.0,1.332268e-15,0.142857
2021-06-20,0.0,0.000000,0.000000,1.428571e-01,0.285714,0.285714,0.142857,0.000000,0.000000,0.142857,...,0.0,0.142857,5.329071e-15,0.000000,0.0,0.142857,0.285714,0.0,1.332268e-15,0.142857
2021-06-21,0.0,0.000000,0.000000,1.428571e-01,0.285714,0.285714,0.142857,0.285714,0.000000,0.142857,...,0.0,0.285714,5.329071e-15,0.000000,0.0,0.142857,0.285714,0.0,1.332268e-15,0.142857
2021-06-22,0.0,0.000000,0.000000,1.428571e-01,0.285714,0.142857,0.142857,0.571429,0.000000,0.142857,...,0.0,0.285714,5.329071e-15,0.000000,0.0,0.142857,0.428571,0.0,1.332268e-15,0.142857
2021-06-23,0.0,0.000000,0.000000,1.428571e-01,0.142857,0.142857,0.142857,0.571429,0.000000,0.142857,...,0.0,0.285714,5.329071e-15,0.000000,0.0,0.142857,0.428571,0.0,1.332268e-15,0.142857
2021-06-24,0.0,0.000000,0.000000,1.428571e-01,0.428571,0.142857,0.142857,0.714286,0.000000,0.142857,...,0.0,0.285714,5.329071e-15,0.000000,0.0,0.142857,0.571429,0.0,1.332268e-15,0.142857
2021-06-25,0.0,0.000000,0.000000,1.428571e-01,0.714286,0.142857,0.142857,0.714286,0.000000,0.142857,...,0.0,0.142857,1.428571e-01,0.000000,0.0,0.142857,0.571429,0.0,1.332268e-15,0.142857
2021-06-26,0.0,0.000000,0.000000,5.551115e-17,0.857143,0.142857,0.142857,0.714286,0.000000,0.142857,...,0.0,0.285714,1.428571e-01,0.142857,0.0,0.000000,0.571429,0.0,1.332268e-15,0.142857
2021-06-27,0.0,0.000000,0.000000,5.551115e-17,0.714286,0.142857,0.000000,0.714286,0.000000,0.000000,...,0.0,0.285714,1.428571e-01,0.142857,0.0,0.142857,0.428571,0.0,1.332268e-15,0.142857
2021-06-28,0.0,0.000000,0.000000,5.551115e-17,0.714286,0.142857,0.000000,0.428571,0.142857,0.000000,...,0.0,0.428571,1.428571e-01,0.142857,0.0,0.142857,0.285714,0.0,1.332268e-15,0.142857
2021-06-29,0.0,0.000000,0.000000,5.551115e-17,0.714286,0.000000,0.000000,0.142857,0.285714,0.000000,...,0.0,0.428571,1.428571e-01,0.142857,0.0,0.142857,0.142857,0.0,1.332268e-15,0.142857
2021-06-30,0.0,0.000000,0.000000,5.551115e-17,0.714286,0.000000,0.000000,0.142857,0.285714,0.000000,...,0.0,0.428571,1.428571e-01,0.142857,0.0,0.142857,0.142857,0.0,1.332268e-15,0.142857
2021-07-01,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000e+00,0.000000,0.0,0.000000,0.000000,0.0,0.000000e+00,0.000000
2021-07-02,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000e+00,0.000000,0.0,0.000000,0.000000,0.0,0.000000e+00,0.000000
2021-07-03,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000e+00,0.000000,0.0,0.000000,0.000000,0.0,0.000000e+00,0.000000
2021-07-04,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000e+00,0.000000,0.0,0.000000,0.000000,0.0,0.000000e+00,0.000000
2021-07-05,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000e+00,0.000000,0.0,0.000000,0.000000,0.0,0.000000e+00,0.000000
2021-07-06,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000e+00,0.000000,0.0,0.000000,0.000000,0.0,0.000000e+00,0.000000
2021-07-07,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000e+00,0.000000,0.0,0.000000,0.000000,0.0,0.000000e+00,0.000000
2021-07-08,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000e+00,0.000000,0.0,0.000000,0.000000,0.0,0.000000e+00,0.000000
2021-07-09,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000e+00,0.000000,0.0,0.000000,0.000000,0.0,0.000000e+00,0.000000
2021-07-10,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000e+00,0.000000,0.0,0.000000,0.000000,0.0,0.000000e+00,0.000000
2021-07-11,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000e+00,0.000000,0.0,0.000000,0.000000,0.0,0.000000e+00,0.000000
2021-07-12,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000e+00,0.000000,0.0,0.000000,0.000000,0.0,0.000000e+00,0.000000
2021-07-13,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000e+00,0.000000,0.0,0.000000,0.000000,0.0,0.000000e+00,0.000000
2021-07-14,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000e+00,0.000000,0.0,0.000000,0.000000,0.0,0.000000e+00,0.000000

In [34]:
df_d = df_d.stack().copy()
df_d

Date        CAName
2020-02-28  Aberdeen City          0.0
            Aberdeenshire          0.0
            Angus                  0.0
            Argyll & Bute          0.0
            City of Edinburgh      0.0
                                  ...
2021-07-14  South Ayrshire         0.0
            South Lanarkshire      0.0
            Stirling               0.0
            West Dunbartonshire    0.0
            West Lothian           0.0
Length: 16096, dtype: float64

In [35]:
df_d1 = df_d.to_frame().reset_index()
df_d1.set_index('Date',inplace=True)
df_d1.rename(columns={'CAName':'Council',0:'Deaths_per_LA'}, inplace=True)
df_d1.Deaths_per_LA = df_d1.Deaths_per_LA.round(0).astype(int)
df_d1.tail(30)

                        Council  Deaths_per_LA
Date
2021-07-14                Angus              0
2021-07-14        Argyll & Bute              0
2021-07-14    City of Edinburgh              0
2021-07-14     Clackmannanshire              0
2021-07-14  Dumfries & Galloway              0
2021-07-14          Dundee City              0
2021-07-14        East Ayrshire              0
2021-07-14  East Dunbartonshire              0
2021-07-14         East Lothian              0
2021-07-14    East Renfrewshire              0
2021-07-14              Falkirk              0
2021-07-14                 Fife              0
2021-07-14         Glasgow City              0
2021-07-14             Highland              0
2021-07-14           Inverclyde              0
2021-07-14           Midlothian              0
2021-07-14                Moray              0
2021-07-14   Na h-Eileanan Siar              0
2021-07-14       North Ayrshire              0
2021-07-14    North Lanarkshire              0
2021-07-14       Orkney Islands              0
2021-07-14      Perth & Kinross              0
2021-07-14         Renfrewshire              0
2021-07-14     Scottish Borders              0
2021-07-14     Shetland Islands              0
2021-07-14       South Ayrshire              0
2021-07-14    South Lanarkshire              0
2021-07-14             Stirling              0
2021-07-14  West Dunbartonshire              0
2021-07-14         West Lothian              0

In [36]:
deaths = df_d1.loc[(df_d1.index>='2021-01-05')&(df_d1.index<='2021-06-30')]
deaths.to_csv('output_deaths_la.csv')
#deaths.tail()

In [178]:
m = deaths.loc[deaths.Council =='Midlothian']
m.describe()

       Deaths_gr_LA
count    146.000000
mean       1.550619
std        2.758375
min        0.000000
25%        0.683896
50%        0.962679
75%        1.312642
max       22.000000